//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace winAppSAIC.ThreeBits {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wserviceBinding", Namespace="urn:wservicewsdl")]
    public partial class wservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback timbrarOperationCompleted;
        
        private System.Threading.SendOrPostCallback timbrarNETOperationCompleted;
        
        private System.Threading.SendOrPostCallback timbrar64OperationCompleted;
        
        private System.Threading.SendOrPostCallback retencionOperationCompleted;
        
        private System.Threading.SendOrPostCallback saldoOperationCompleted;
        
        private System.Threading.SendOrPostCallback saldoNETOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelarOperationCompleted;
        
        private System.Threading.SendOrPostCallback generar_pemOperationCompleted;
        
        private System.Threading.SendOrPostCallback respaldo_masivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ticketOperationCompleted;
        
        private System.Threading.SendOrPostCallback ticket_reporteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ticket_cancelaOperationCompleted;
        
        private System.Threading.SendOrPostCallback factura_reporteOperationCompleted;
        
        private System.Threading.SendOrPostCallback factura_recupera_respaldoOperationCompleted;
        
        private System.Threading.SendOrPostCallback genera_dotnetOperationCompleted;
        
        private System.Threading.SendOrPostCallback genera_ut8OperationCompleted;
        
        private System.Threading.SendOrPostCallback acuseSATOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancela_ut8OperationCompleted;
        
        private System.Threading.SendOrPostCallback timbradoMICROSIPOperationCompleted;
        
        private System.Threading.SendOrPostCallback timbrar33b64OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wservice() {
            this.Url = global::winAppSAIC.Properties.Settings.Default.winAppSAIC_ThreeBits_wservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event timbrarCompletedEventHandler timbrarCompleted;
        
        /// <remarks/>
        public event timbrarNETCompletedEventHandler timbrarNETCompleted;
        
        /// <remarks/>
        public event timbrar64CompletedEventHandler timbrar64Completed;
        
        /// <remarks/>
        public event retencionCompletedEventHandler retencionCompleted;
        
        /// <remarks/>
        public event saldoCompletedEventHandler saldoCompleted;
        
        /// <remarks/>
        public event saldoNETCompletedEventHandler saldoNETCompleted;
        
        /// <remarks/>
        public event cancelarCompletedEventHandler cancelarCompleted;
        
        /// <remarks/>
        public event generar_pemCompletedEventHandler generar_pemCompleted;
        
        /// <remarks/>
        public event respaldo_masivoCompletedEventHandler respaldo_masivoCompleted;
        
        /// <remarks/>
        public event ticketCompletedEventHandler ticketCompleted;
        
        /// <remarks/>
        public event ticket_reporteCompletedEventHandler ticket_reporteCompleted;
        
        /// <remarks/>
        public event ticket_cancelaCompletedEventHandler ticket_cancelaCompleted;
        
        /// <remarks/>
        public event factura_reporteCompletedEventHandler factura_reporteCompleted;
        
        /// <remarks/>
        public event factura_recupera_respaldoCompletedEventHandler factura_recupera_respaldoCompleted;
        
        /// <remarks/>
        public event genera_dotnetCompletedEventHandler genera_dotnetCompleted;
        
        /// <remarks/>
        public event genera_ut8CompletedEventHandler genera_ut8Completed;
        
        /// <remarks/>
        public event acuseSATCompletedEventHandler acuseSATCompleted;
        
        /// <remarks/>
        public event cancela_ut8CompletedEventHandler cancela_ut8Completed;
        
        /// <remarks/>
        public event timbradoMICROSIPCompletedEventHandler timbradoMICROSIPCompleted;
        
        /// <remarks/>
        public event timbrar33b64CompletedEventHandler timbrar33b64Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#timbrar", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string timbrar(string rfc, string clave, string xml, string produccion) {
            object[] results = this.Invoke("timbrar", new object[] {
                        rfc,
                        clave,
                        xml,
                        produccion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void timbrarAsync(string rfc, string clave, string xml, string produccion) {
            this.timbrarAsync(rfc, clave, xml, produccion, null);
        }
        
        /// <remarks/>
        public void timbrarAsync(string rfc, string clave, string xml, string produccion, object userState) {
            if ((this.timbrarOperationCompleted == null)) {
                this.timbrarOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbrarOperationCompleted);
            }
            this.InvokeAsync("timbrar", new object[] {
                        rfc,
                        clave,
                        xml,
                        produccion}, this.timbrarOperationCompleted, userState);
        }
        
        private void OntimbrarOperationCompleted(object arg) {
            if ((this.timbrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbrarCompleted(this, new timbrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#timbrar", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public RespuestaNET timbrarNET(string rfc, string clave, string xml, string produccion) {
            object[] results = this.Invoke("timbrarNET", new object[] {
                        rfc,
                        clave,
                        xml,
                        produccion});
            return ((RespuestaNET)(results[0]));
        }
        
        /// <remarks/>
        public void timbrarNETAsync(string rfc, string clave, string xml, string produccion) {
            this.timbrarNETAsync(rfc, clave, xml, produccion, null);
        }
        
        /// <remarks/>
        public void timbrarNETAsync(string rfc, string clave, string xml, string produccion, object userState) {
            if ((this.timbrarNETOperationCompleted == null)) {
                this.timbrarNETOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbrarNETOperationCompleted);
            }
            this.InvokeAsync("timbrarNET", new object[] {
                        rfc,
                        clave,
                        xml,
                        produccion}, this.timbrarNETOperationCompleted, userState);
        }
        
        private void OntimbrarNETOperationCompleted(object arg) {
            if ((this.timbrarNETCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbrarNETCompleted(this, new timbrarNETCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#timbrar64", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string timbrar64(string rfc, string clave, string xml, string produccion) {
            object[] results = this.Invoke("timbrar64", new object[] {
                        rfc,
                        clave,
                        xml,
                        produccion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void timbrar64Async(string rfc, string clave, string xml, string produccion) {
            this.timbrar64Async(rfc, clave, xml, produccion, null);
        }
        
        /// <remarks/>
        public void timbrar64Async(string rfc, string clave, string xml, string produccion, object userState) {
            if ((this.timbrar64OperationCompleted == null)) {
                this.timbrar64OperationCompleted = new System.Threading.SendOrPostCallback(this.Ontimbrar64OperationCompleted);
            }
            this.InvokeAsync("timbrar64", new object[] {
                        rfc,
                        clave,
                        xml,
                        produccion}, this.timbrar64OperationCompleted, userState);
        }
        
        private void Ontimbrar64OperationCompleted(object arg) {
            if ((this.timbrar64Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbrar64Completed(this, new timbrar64CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#timbrar", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string retencion(string rfc, string clave, string xml, string produccion) {
            object[] results = this.Invoke("retencion", new object[] {
                        rfc,
                        clave,
                        xml,
                        produccion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void retencionAsync(string rfc, string clave, string xml, string produccion) {
            this.retencionAsync(rfc, clave, xml, produccion, null);
        }
        
        /// <remarks/>
        public void retencionAsync(string rfc, string clave, string xml, string produccion, object userState) {
            if ((this.retencionOperationCompleted == null)) {
                this.retencionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretencionOperationCompleted);
            }
            this.InvokeAsync("retencion", new object[] {
                        rfc,
                        clave,
                        xml,
                        produccion}, this.retencionOperationCompleted, userState);
        }
        
        private void OnretencionOperationCompleted(object arg) {
            if ((this.retencionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retencionCompleted(this, new retencionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#saldo", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string saldo(string rfc, string clave) {
            object[] results = this.Invoke("saldo", new object[] {
                        rfc,
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saldoAsync(string rfc, string clave) {
            this.saldoAsync(rfc, clave, null);
        }
        
        /// <remarks/>
        public void saldoAsync(string rfc, string clave, object userState) {
            if ((this.saldoOperationCompleted == null)) {
                this.saldoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaldoOperationCompleted);
            }
            this.InvokeAsync("saldo", new object[] {
                        rfc,
                        clave}, this.saldoOperationCompleted, userState);
        }
        
        private void OnsaldoOperationCompleted(object arg) {
            if ((this.saldoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saldoCompleted(this, new saldoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#saldoNET", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public saldoResponse saldoNET(string rfc, string clave) {
            object[] results = this.Invoke("saldoNET", new object[] {
                        rfc,
                        clave});
            return ((saldoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void saldoNETAsync(string rfc, string clave) {
            this.saldoNETAsync(rfc, clave, null);
        }
        
        /// <remarks/>
        public void saldoNETAsync(string rfc, string clave, object userState) {
            if ((this.saldoNETOperationCompleted == null)) {
                this.saldoNETOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaldoNETOperationCompleted);
            }
            this.InvokeAsync("saldoNET", new object[] {
                        rfc,
                        clave}, this.saldoNETOperationCompleted, userState);
        }
        
        private void OnsaldoNETOperationCompleted(object arg) {
            if ((this.saldoNETCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saldoNETCompleted(this, new saldoNETCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#cancelar", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string cancelar(string rfc, string clave, string uuid, string cer, string key, string pass_cer) {
            object[] results = this.Invoke("cancelar", new object[] {
                        rfc,
                        clave,
                        uuid,
                        cer,
                        key,
                        pass_cer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarAsync(string rfc, string clave, string uuid, string cer, string key, string pass_cer) {
            this.cancelarAsync(rfc, clave, uuid, cer, key, pass_cer, null);
        }
        
        /// <remarks/>
        public void cancelarAsync(string rfc, string clave, string uuid, string cer, string key, string pass_cer, object userState) {
            if ((this.cancelarOperationCompleted == null)) {
                this.cancelarOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarOperationCompleted);
            }
            this.InvokeAsync("cancelar", new object[] {
                        rfc,
                        clave,
                        uuid,
                        cer,
                        key,
                        pass_cer}, this.cancelarOperationCompleted, userState);
        }
        
        private void OncancelarOperationCompleted(object arg) {
            if ((this.cancelarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarCompleted(this, new cancelarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#generar_pem", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string generar_pem(string cer_base64, string key_base64, string pass_base64) {
            object[] results = this.Invoke("generar_pem", new object[] {
                        cer_base64,
                        key_base64,
                        pass_base64});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void generar_pemAsync(string cer_base64, string key_base64, string pass_base64) {
            this.generar_pemAsync(cer_base64, key_base64, pass_base64, null);
        }
        
        /// <remarks/>
        public void generar_pemAsync(string cer_base64, string key_base64, string pass_base64, object userState) {
            if ((this.generar_pemOperationCompleted == null)) {
                this.generar_pemOperationCompleted = new System.Threading.SendOrPostCallback(this.Ongenerar_pemOperationCompleted);
            }
            this.InvokeAsync("generar_pem", new object[] {
                        cer_base64,
                        key_base64,
                        pass_base64}, this.generar_pemOperationCompleted, userState);
        }
        
        private void Ongenerar_pemOperationCompleted(object arg) {
            if ((this.generar_pemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generar_pemCompleted(this, new generar_pemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#ticket", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string respaldo_masivo(string rfc, string clave, string respaldo_base64) {
            object[] results = this.Invoke("respaldo_masivo", new object[] {
                        rfc,
                        clave,
                        respaldo_base64});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void respaldo_masivoAsync(string rfc, string clave, string respaldo_base64) {
            this.respaldo_masivoAsync(rfc, clave, respaldo_base64, null);
        }
        
        /// <remarks/>
        public void respaldo_masivoAsync(string rfc, string clave, string respaldo_base64, object userState) {
            if ((this.respaldo_masivoOperationCompleted == null)) {
                this.respaldo_masivoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onrespaldo_masivoOperationCompleted);
            }
            this.InvokeAsync("respaldo_masivo", new object[] {
                        rfc,
                        clave,
                        respaldo_base64}, this.respaldo_masivoOperationCompleted, userState);
        }
        
        private void Onrespaldo_masivoOperationCompleted(object arg) {
            if ((this.respaldo_masivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.respaldo_masivoCompleted(this, new respaldo_masivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#ticket", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ticket(string rfc, string clave, [System.Xml.Serialization.SoapElementAttribute("ticket")] string ticket1, string produccion) {
            object[] results = this.Invoke("ticket", new object[] {
                        rfc,
                        clave,
                        ticket1,
                        produccion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ticketAsync(string rfc, string clave, string ticket1, string produccion) {
            this.ticketAsync(rfc, clave, ticket1, produccion, null);
        }
        
        /// <remarks/>
        public void ticketAsync(string rfc, string clave, string ticket1, string produccion, object userState) {
            if ((this.ticketOperationCompleted == null)) {
                this.ticketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnticketOperationCompleted);
            }
            this.InvokeAsync("ticket", new object[] {
                        rfc,
                        clave,
                        ticket1,
                        produccion}, this.ticketOperationCompleted, userState);
        }
        
        private void OnticketOperationCompleted(object arg) {
            if ((this.ticketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ticketCompleted(this, new ticketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#ticket_reporte", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ticket_reporte(string rfc, string clave, string tipo, string fecha_inicial, string fecha_final) {
            object[] results = this.Invoke("ticket_reporte", new object[] {
                        rfc,
                        clave,
                        tipo,
                        fecha_inicial,
                        fecha_final});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ticket_reporteAsync(string rfc, string clave, string tipo, string fecha_inicial, string fecha_final) {
            this.ticket_reporteAsync(rfc, clave, tipo, fecha_inicial, fecha_final, null);
        }
        
        /// <remarks/>
        public void ticket_reporteAsync(string rfc, string clave, string tipo, string fecha_inicial, string fecha_final, object userState) {
            if ((this.ticket_reporteOperationCompleted == null)) {
                this.ticket_reporteOperationCompleted = new System.Threading.SendOrPostCallback(this.Onticket_reporteOperationCompleted);
            }
            this.InvokeAsync("ticket_reporte", new object[] {
                        rfc,
                        clave,
                        tipo,
                        fecha_inicial,
                        fecha_final}, this.ticket_reporteOperationCompleted, userState);
        }
        
        private void Onticket_reporteOperationCompleted(object arg) {
            if ((this.ticket_reporteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ticket_reporteCompleted(this, new ticket_reporteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#ticket_reporte", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ticket_cancela(string rfc, string clave, string codigo) {
            object[] results = this.Invoke("ticket_cancela", new object[] {
                        rfc,
                        clave,
                        codigo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ticket_cancelaAsync(string rfc, string clave, string codigo) {
            this.ticket_cancelaAsync(rfc, clave, codigo, null);
        }
        
        /// <remarks/>
        public void ticket_cancelaAsync(string rfc, string clave, string codigo, object userState) {
            if ((this.ticket_cancelaOperationCompleted == null)) {
                this.ticket_cancelaOperationCompleted = new System.Threading.SendOrPostCallback(this.Onticket_cancelaOperationCompleted);
            }
            this.InvokeAsync("ticket_cancela", new object[] {
                        rfc,
                        clave,
                        codigo}, this.ticket_cancelaOperationCompleted, userState);
        }
        
        private void Onticket_cancelaOperationCompleted(object arg) {
            if ((this.ticket_cancelaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ticket_cancelaCompleted(this, new ticket_cancelaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#factura_reporte", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string factura_reporte(string rfc, string clave, string mes, string ano) {
            object[] results = this.Invoke("factura_reporte", new object[] {
                        rfc,
                        clave,
                        mes,
                        ano});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void factura_reporteAsync(string rfc, string clave, string mes, string ano) {
            this.factura_reporteAsync(rfc, clave, mes, ano, null);
        }
        
        /// <remarks/>
        public void factura_reporteAsync(string rfc, string clave, string mes, string ano, object userState) {
            if ((this.factura_reporteOperationCompleted == null)) {
                this.factura_reporteOperationCompleted = new System.Threading.SendOrPostCallback(this.Onfactura_reporteOperationCompleted);
            }
            this.InvokeAsync("factura_reporte", new object[] {
                        rfc,
                        clave,
                        mes,
                        ano}, this.factura_reporteOperationCompleted, userState);
        }
        
        private void Onfactura_reporteOperationCompleted(object arg) {
            if ((this.factura_reporteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.factura_reporteCompleted(this, new factura_reporteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#factura_respaldo", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string factura_recupera_respaldo(string rfc, string clave, string referencia, string uuid) {
            object[] results = this.Invoke("factura_recupera_respaldo", new object[] {
                        rfc,
                        clave,
                        referencia,
                        uuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void factura_recupera_respaldoAsync(string rfc, string clave, string referencia, string uuid) {
            this.factura_recupera_respaldoAsync(rfc, clave, referencia, uuid, null);
        }
        
        /// <remarks/>
        public void factura_recupera_respaldoAsync(string rfc, string clave, string referencia, string uuid, object userState) {
            if ((this.factura_recupera_respaldoOperationCompleted == null)) {
                this.factura_recupera_respaldoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onfactura_recupera_respaldoOperationCompleted);
            }
            this.InvokeAsync("factura_recupera_respaldo", new object[] {
                        rfc,
                        clave,
                        referencia,
                        uuid}, this.factura_recupera_respaldoOperationCompleted, userState);
        }
        
        private void Onfactura_recupera_respaldoOperationCompleted(object arg) {
            if ((this.factura_recupera_respaldoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.factura_recupera_respaldoCompleted(this, new factura_recupera_respaldoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#genera_dotnet", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string genera_dotnet(string empresa, string pwd, string fe_xml) {
            object[] results = this.Invoke("genera_dotnet", new object[] {
                        empresa,
                        pwd,
                        fe_xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void genera_dotnetAsync(string empresa, string pwd, string fe_xml) {
            this.genera_dotnetAsync(empresa, pwd, fe_xml, null);
        }
        
        /// <remarks/>
        public void genera_dotnetAsync(string empresa, string pwd, string fe_xml, object userState) {
            if ((this.genera_dotnetOperationCompleted == null)) {
                this.genera_dotnetOperationCompleted = new System.Threading.SendOrPostCallback(this.Ongenera_dotnetOperationCompleted);
            }
            this.InvokeAsync("genera_dotnet", new object[] {
                        empresa,
                        pwd,
                        fe_xml}, this.genera_dotnetOperationCompleted, userState);
        }
        
        private void Ongenera_dotnetOperationCompleted(object arg) {
            if ((this.genera_dotnetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.genera_dotnetCompleted(this, new genera_dotnetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#genera_ut8", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string genera_ut8(string rfc, string clave, string xml) {
            object[] results = this.Invoke("genera_ut8", new object[] {
                        rfc,
                        clave,
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void genera_ut8Async(string rfc, string clave, string xml) {
            this.genera_ut8Async(rfc, clave, xml, null);
        }
        
        /// <remarks/>
        public void genera_ut8Async(string rfc, string clave, string xml, object userState) {
            if ((this.genera_ut8OperationCompleted == null)) {
                this.genera_ut8OperationCompleted = new System.Threading.SendOrPostCallback(this.Ongenera_ut8OperationCompleted);
            }
            this.InvokeAsync("genera_ut8", new object[] {
                        rfc,
                        clave,
                        xml}, this.genera_ut8OperationCompleted, userState);
        }
        
        private void Ongenera_ut8OperationCompleted(object arg) {
            if ((this.genera_ut8Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.genera_ut8Completed(this, new genera_ut8CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#acuseSAT", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string acuseSAT(string rfc, string pwd, string uuid) {
            object[] results = this.Invoke("acuseSAT", new object[] {
                        rfc,
                        pwd,
                        uuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void acuseSATAsync(string rfc, string pwd, string uuid) {
            this.acuseSATAsync(rfc, pwd, uuid, null);
        }
        
        /// <remarks/>
        public void acuseSATAsync(string rfc, string pwd, string uuid, object userState) {
            if ((this.acuseSATOperationCompleted == null)) {
                this.acuseSATOperationCompleted = new System.Threading.SendOrPostCallback(this.OnacuseSATOperationCompleted);
            }
            this.InvokeAsync("acuseSAT", new object[] {
                        rfc,
                        pwd,
                        uuid}, this.acuseSATOperationCompleted, userState);
        }
        
        private void OnacuseSATOperationCompleted(object arg) {
            if ((this.acuseSATCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.acuseSATCompleted(this, new acuseSATCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#cancela_ut8", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string cancela_ut8(string rfc, string pwd, string xml_in) {
            object[] results = this.Invoke("cancela_ut8", new object[] {
                        rfc,
                        pwd,
                        xml_in});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cancela_ut8Async(string rfc, string pwd, string xml_in) {
            this.cancela_ut8Async(rfc, pwd, xml_in, null);
        }
        
        /// <remarks/>
        public void cancela_ut8Async(string rfc, string pwd, string xml_in, object userState) {
            if ((this.cancela_ut8OperationCompleted == null)) {
                this.cancela_ut8OperationCompleted = new System.Threading.SendOrPostCallback(this.Oncancela_ut8OperationCompleted);
            }
            this.InvokeAsync("cancela_ut8", new object[] {
                        rfc,
                        pwd,
                        xml_in}, this.cancela_ut8OperationCompleted, userState);
        }
        
        private void Oncancela_ut8OperationCompleted(object arg) {
            if ((this.cancela_ut8Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancela_ut8Completed(this, new cancela_ut8CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#timbradoMicrosip", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string timbradoMICROSIP(string rfc, string clave, string tipo, string xml, string produccion) {
            object[] results = this.Invoke("timbradoMICROSIP", new object[] {
                        rfc,
                        clave,
                        tipo,
                        xml,
                        produccion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void timbradoMICROSIPAsync(string rfc, string clave, string tipo, string xml, string produccion) {
            this.timbradoMICROSIPAsync(rfc, clave, tipo, xml, produccion, null);
        }
        
        /// <remarks/>
        public void timbradoMICROSIPAsync(string rfc, string clave, string tipo, string xml, string produccion, object userState) {
            if ((this.timbradoMICROSIPOperationCompleted == null)) {
                this.timbradoMICROSIPOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbradoMICROSIPOperationCompleted);
            }
            this.InvokeAsync("timbradoMICROSIP", new object[] {
                        rfc,
                        clave,
                        tipo,
                        xml,
                        produccion}, this.timbradoMICROSIPOperationCompleted, userState);
        }
        
        private void OntimbradoMICROSIPOperationCompleted(object arg) {
            if ((this.timbradoMICROSIPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbradoMICROSIPCompleted(this, new timbradoMICROSIPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wservicewsdl#timbrar33b64", RequestNamespace="urn:wservicewsdl", ResponseNamespace="urn:wservicewsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public RespuestaNET timbrar33b64(string rfc, string clave, string xml, string produccion) {
            object[] results = this.Invoke("timbrar33b64", new object[] {
                        rfc,
                        clave,
                        xml,
                        produccion});
            return ((RespuestaNET)(results[0]));
        }
        
        /// <remarks/>
        public void timbrar33b64Async(string rfc, string clave, string xml, string produccion) {
            this.timbrar33b64Async(rfc, clave, xml, produccion, null);
        }
        
        /// <remarks/>
        public void timbrar33b64Async(string rfc, string clave, string xml, string produccion, object userState) {
            if ((this.timbrar33b64OperationCompleted == null)) {
                this.timbrar33b64OperationCompleted = new System.Threading.SendOrPostCallback(this.Ontimbrar33b64OperationCompleted);
            }
            this.InvokeAsync("timbrar33b64", new object[] {
                        rfc,
                        clave,
                        xml,
                        produccion}, this.timbrar33b64OperationCompleted, userState);
        }
        
        private void Ontimbrar33b64OperationCompleted(object arg) {
            if ((this.timbrar33b64Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbrar33b64Completed(this, new timbrar33b64CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:wservicewsdl")]
    public partial class RespuestaNET {
        
        private string cfdiField;
        
        private string pngField;
        
        private int idpacField;
        
        private int pacField;
        
        private string produccionField;
        
        private int codigo_mf_numeroField;
        
        private string codigo_mf_textoField;
        
        private string mensaje_original_pac_jsonField;
        
        private string canceladaField;
        
        private int saldoField;
        
        private string uuidField;
        
        private string servidorField;
        
        private float ejecucionField;
        
        private string debugField;
        
        /// <remarks/>
        public string cfdi {
            get {
                return this.cfdiField;
            }
            set {
                this.cfdiField = value;
            }
        }
        
        /// <remarks/>
        public string png {
            get {
                return this.pngField;
            }
            set {
                this.pngField = value;
            }
        }
        
        /// <remarks/>
        public int idpac {
            get {
                return this.idpacField;
            }
            set {
                this.idpacField = value;
            }
        }
        
        /// <remarks/>
        public int pac {
            get {
                return this.pacField;
            }
            set {
                this.pacField = value;
            }
        }
        
        /// <remarks/>
        public string produccion {
            get {
                return this.produccionField;
            }
            set {
                this.produccionField = value;
            }
        }
        
        /// <remarks/>
        public int codigo_mf_numero {
            get {
                return this.codigo_mf_numeroField;
            }
            set {
                this.codigo_mf_numeroField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_mf_texto {
            get {
                return this.codigo_mf_textoField;
            }
            set {
                this.codigo_mf_textoField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje_original_pac_json {
            get {
                return this.mensaje_original_pac_jsonField;
            }
            set {
                this.mensaje_original_pac_jsonField = value;
            }
        }
        
        /// <remarks/>
        public string cancelada {
            get {
                return this.canceladaField;
            }
            set {
                this.canceladaField = value;
            }
        }
        
        /// <remarks/>
        public int saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        public string servidor {
            get {
                return this.servidorField;
            }
            set {
                this.servidorField = value;
            }
        }
        
        /// <remarks/>
        public float ejecucion {
            get {
                return this.ejecucionField;
            }
            set {
                this.ejecucionField = value;
            }
        }
        
        /// <remarks/>
        public string debug {
            get {
                return this.debugField;
            }
            set {
                this.debugField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:wservicewsdl")]
    public partial class saldoResponse {
        
        private string saldoResultField;
        
        private int saldoField;
        
        /// <remarks/>
        public string saldoResult {
            get {
                return this.saldoResultField;
            }
            set {
                this.saldoResultField = value;
            }
        }
        
        /// <remarks/>
        public int saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void timbrarCompletedEventHandler(object sender, timbrarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbrarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbrarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void timbrarNETCompletedEventHandler(object sender, timbrarNETCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbrarNETCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbrarNETCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaNET Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaNET)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void timbrar64CompletedEventHandler(object sender, timbrar64CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbrar64CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbrar64CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void retencionCompletedEventHandler(object sender, retencionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retencionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retencionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void saldoCompletedEventHandler(object sender, saldoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saldoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saldoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void saldoNETCompletedEventHandler(object sender, saldoNETCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saldoNETCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saldoNETCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public saldoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((saldoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cancelarCompletedEventHandler(object sender, cancelarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void generar_pemCompletedEventHandler(object sender, generar_pemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generar_pemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generar_pemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void respaldo_masivoCompletedEventHandler(object sender, respaldo_masivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class respaldo_masivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal respaldo_masivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ticketCompletedEventHandler(object sender, ticketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ticketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ticketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ticket_reporteCompletedEventHandler(object sender, ticket_reporteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ticket_reporteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ticket_reporteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ticket_cancelaCompletedEventHandler(object sender, ticket_cancelaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ticket_cancelaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ticket_cancelaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void factura_reporteCompletedEventHandler(object sender, factura_reporteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class factura_reporteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal factura_reporteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void factura_recupera_respaldoCompletedEventHandler(object sender, factura_recupera_respaldoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class factura_recupera_respaldoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal factura_recupera_respaldoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void genera_dotnetCompletedEventHandler(object sender, genera_dotnetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class genera_dotnetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal genera_dotnetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void genera_ut8CompletedEventHandler(object sender, genera_ut8CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class genera_ut8CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal genera_ut8CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void acuseSATCompletedEventHandler(object sender, acuseSATCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class acuseSATCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal acuseSATCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cancela_ut8CompletedEventHandler(object sender, cancela_ut8CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancela_ut8CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancela_ut8CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void timbradoMICROSIPCompletedEventHandler(object sender, timbradoMICROSIPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbradoMICROSIPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbradoMICROSIPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void timbrar33b64CompletedEventHandler(object sender, timbrar33b64CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbrar33b64CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbrar33b64CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaNET Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaNET)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591