//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winAppSAIC.srvComEnlaceFiscalAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.enlacefiscal.namespace", ConfigurationName="srvComEnlaceFiscalAPI.wsAPIxmlSOAP")]
    public interface wsAPIxmlSOAP {
        
        // CODEGEN: Generating message contract since the operation generarAsalariado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/generarAsalariado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.generarAsalariadoResponse generarAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.generarAsalariadoRequest request);
        
        // CODEGEN: Generating message contract since the operation generarAsimilable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/generarAsimilable", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.generarAsimilableResponse generarAsimilable(winAppSAIC.srvComEnlaceFiscalAPI.generarAsimilableRequest request);
        
        // CODEGEN: Generating message contract since the operation generarPensionado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/generarPensionado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.generarPensionadoResponse generarPensionado(winAppSAIC.srvComEnlaceFiscalAPI.generarPensionadoRequest request);
        
        // CODEGEN: Generating message contract since the operation generarJubilado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/generarJubilado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.generarJubiladoResponse generarJubilado(winAppSAIC.srvComEnlaceFiscalAPI.generarJubiladoRequest request);
        
        // CODEGEN: Generating message contract since the operation recuperarAsalariado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/recuperarAsalariado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.recuperarAsalariadoResponse recuperarAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.recuperarAsalariadoRequest request);
        
        // CODEGEN: Generating message contract since the operation informacionAsalariado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/informacionAsalariado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.informacionAsalariadoResponse informacionAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.informacionAsalariadoRequest request);
        
        // CODEGEN: Generating message contract since the operation informacionAsimilable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/informacionAsimilable", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.informacionAsimilableResponse informacionAsimilable(winAppSAIC.srvComEnlaceFiscalAPI.informacionAsimilableRequest request);
        
        // CODEGEN: Generating message contract since the operation informacionPensionado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/informacionPensionado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.informacionPensionadoResponse informacionPensionado(winAppSAIC.srvComEnlaceFiscalAPI.informacionPensionadoRequest request);
        
        // CODEGEN: Generating message contract since the operation informacionJubilado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/informacionJubilado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.informacionJubiladoResponse informacionJubilado(winAppSAIC.srvComEnlaceFiscalAPI.informacionJubiladoRequest request);
        
        // CODEGEN: Generating message contract since the operation cancelarAsalariado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/cancelarAsalariado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.cancelarAsalariadoResponse cancelarAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.cancelarAsalariadoRequest request);
        
        // CODEGEN: Generating message contract since the operation cancelarAsimilable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/cancelarAsimilable", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.cancelarAsimilableResponse cancelarAsimilable(winAppSAIC.srvComEnlaceFiscalAPI.cancelarAsimilableRequest request);
        
        // CODEGEN: Generating message contract since the operation cancelarPensionado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/cancelarPensionado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.cancelarPensionadoResponse cancelarPensionado(winAppSAIC.srvComEnlaceFiscalAPI.cancelarPensionadoRequest request);
        
        // CODEGEN: Generating message contract since the operation cancelarJubilado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/cancelarJubilado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.cancelarJubiladoResponse cancelarJubilado(winAppSAIC.srvComEnlaceFiscalAPI.cancelarJubiladoRequest request);
        
        // CODEGEN: Generating message contract since the operation obtenerSaldo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/obtenerSaldo", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.obtenerSaldoResponse obtenerSaldo(winAppSAIC.srvComEnlaceFiscalAPI.obtenerSaldoRequest request);
        
        // CODEGEN: Generating message contract since the operation solicitarXmlAsalariado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/solicitarXmlAsalariado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlAsalariadoResponse solicitarXmlAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlAsalariadoRequest request);
        
        // CODEGEN: Generating message contract since the operation solicitarXmlAsimilable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/solicitarXmlAsimilable", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlAsimilableResponse solicitarXmlAsimilable(winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlAsimilableRequest request);
        
        // CODEGEN: Generating message contract since the operation solicitarXmlPensionado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/solicitarXmlPensionado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlPensionadoResponse solicitarXmlPensionado(winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlPensionadoRequest request);
        
        // CODEGEN: Generating message contract since the operation solicitarXmlJubilado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/solicitarXmlJubilado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlJubiladoResponse solicitarXmlJubilado(winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlJubiladoRequest request);
        
        // CODEGEN: Generating message contract since the operation probarConexionAsimilable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/probarConexionAsimilable", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.probarConexionAsimilableResponse probarConexionAsimilable(winAppSAIC.srvComEnlaceFiscalAPI.probarConexionAsimilableRequest request);
        
        // CODEGEN: Generating message contract since the operation probarConexionAsalariado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/probarConexionAsalariado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.probarConexionAsalariadoResponse probarConexionAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.probarConexionAsalariadoRequest request);
        
        // CODEGEN: Generating message contract since the operation probarConexionPensionado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/probarConexionPensionado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.probarConexionPensionadoResponse probarConexionPensionado(winAppSAIC.srvComEnlaceFiscalAPI.probarConexionPensionadoRequest request);
        
        // CODEGEN: Generating message contract since the operation probarConexionJubilado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/probarConexionJubilado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.probarConexionJubiladoResponse probarConexionJubilado(winAppSAIC.srvComEnlaceFiscalAPI.probarConexionJubiladoRequest request);
        
        // CODEGEN: Generating message contract since the operation solicitarQrAsalariado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/solicitarQrAsalariado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrAsalariadoResponse solicitarQrAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrAsalariadoRequest request);
        
        // CODEGEN: Generating message contract since the operation solicitarQrAsimilable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/solicitarQrAsalariado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrAsimilableResponse solicitarQrAsimilable(winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrAsimilableRequest request);
        
        // CODEGEN: Generating message contract since the operation solicitarQrPensionado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/solicitarQrPensionado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrPensionadoResponse solicitarQrPensionado(winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrPensionadoRequest request);
        
        // CODEGEN: Generating message contract since the operation solicitarQrJubilado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/solicitarQrJubilado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrJubiladoResponse solicitarQrJubilado(winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrJubiladoRequest request);
        
        // CODEGEN: Generating message contract since the operation enviarCorreoAsalariado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/enviarCorreoAsalariado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoAsalariadoResponse enviarCorreoAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoAsalariadoRequest request);
        
        // CODEGEN: Generating message contract since the operation enviarCorreoAsimilable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/enviarCorreoAsimilable", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoAsimilableResponse enviarCorreoAsimilable(winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoAsimilableRequest request);
        
        // CODEGEN: Generating message contract since the operation enviarCorreoPensionado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/enviarCorreoPensionado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoPensionadoResponse enviarCorreoPensionado(winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoPensionadoRequest request);
        
        // CODEGEN: Generating message contract since the operation enviarCorreoJubilado is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/enviarCorreoJubilado", ReplyAction="*")]
        winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoJubiladoResponse enviarCorreoJubilado(winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoJubiladoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarAsalariadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string generarAsalariado;
        
        public generarAsalariadoRequest() {
        }
        
        public generarAsalariadoRequest(string generarAsalariado) {
            this.generarAsalariado = generarAsalariado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarAsalariadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string generarAsalariadoResult;
        
        public generarAsalariadoResponse() {
        }
        
        public generarAsalariadoResponse(string generarAsalariadoResult) {
            this.generarAsalariadoResult = generarAsalariadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarAsimilableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string generarAsimilable;
        
        public generarAsimilableRequest() {
        }
        
        public generarAsimilableRequest(string generarAsimilable) {
            this.generarAsimilable = generarAsimilable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarAsimilableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string generarAsimilableResult;
        
        public generarAsimilableResponse() {
        }
        
        public generarAsimilableResponse(string generarAsimilableResult) {
            this.generarAsimilableResult = generarAsimilableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarPensionadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string generarPensionado;
        
        public generarPensionadoRequest() {
        }
        
        public generarPensionadoRequest(string generarPensionado) {
            this.generarPensionado = generarPensionado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarPensionadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string generarPensionadoResult;
        
        public generarPensionadoResponse() {
        }
        
        public generarPensionadoResponse(string generarPensionadoResult) {
            this.generarPensionadoResult = generarPensionadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarJubiladoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string generarJubilado;
        
        public generarJubiladoRequest() {
        }
        
        public generarJubiladoRequest(string generarJubilado) {
            this.generarJubilado = generarJubilado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarJubiladoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string generarJubiladoResult;
        
        public generarJubiladoResponse() {
        }
        
        public generarJubiladoResponse(string generarJubiladoResult) {
            this.generarJubiladoResult = generarJubiladoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recuperarAsalariadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string recuperarAsalariado;
        
        public recuperarAsalariadoRequest() {
        }
        
        public recuperarAsalariadoRequest(string recuperarAsalariado) {
            this.recuperarAsalariado = recuperarAsalariado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recuperarAsalariadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string recuperarAsalariadoResult;
        
        public recuperarAsalariadoResponse() {
        }
        
        public recuperarAsalariadoResponse(string recuperarAsalariadoResult) {
            this.recuperarAsalariadoResult = recuperarAsalariadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class informacionAsalariadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string infoFolio;
        
        public informacionAsalariadoRequest() {
        }
        
        public informacionAsalariadoRequest(string infoFolio) {
            this.infoFolio = infoFolio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class informacionAsalariadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string infoResult;
        
        public informacionAsalariadoResponse() {
        }
        
        public informacionAsalariadoResponse(string infoResult) {
            this.infoResult = infoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class informacionAsimilableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string infoFolio;
        
        public informacionAsimilableRequest() {
        }
        
        public informacionAsimilableRequest(string infoFolio) {
            this.infoFolio = infoFolio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class informacionAsimilableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string infoResult;
        
        public informacionAsimilableResponse() {
        }
        
        public informacionAsimilableResponse(string infoResult) {
            this.infoResult = infoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class informacionPensionadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string infoFolio;
        
        public informacionPensionadoRequest() {
        }
        
        public informacionPensionadoRequest(string infoFolio) {
            this.infoFolio = infoFolio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class informacionPensionadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string infoResult;
        
        public informacionPensionadoResponse() {
        }
        
        public informacionPensionadoResponse(string infoResult) {
            this.infoResult = infoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class informacionJubiladoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string infoFolio;
        
        public informacionJubiladoRequest() {
        }
        
        public informacionJubiladoRequest(string infoFolio) {
            this.infoFolio = infoFolio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class informacionJubiladoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string infoResult;
        
        public informacionJubiladoResponse() {
        }
        
        public informacionJubiladoResponse(string infoResult) {
            this.infoResult = infoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelarAsalariadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cancelarAsalariado;
        
        public cancelarAsalariadoRequest() {
        }
        
        public cancelarAsalariadoRequest(string cancelarAsalariado) {
            this.cancelarAsalariado = cancelarAsalariado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelarAsalariadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cancelarAsalariadoResult;
        
        public cancelarAsalariadoResponse() {
        }
        
        public cancelarAsalariadoResponse(string cancelarAsalariadoResult) {
            this.cancelarAsalariadoResult = cancelarAsalariadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelarAsimilableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cancelarAsimilable;
        
        public cancelarAsimilableRequest() {
        }
        
        public cancelarAsimilableRequest(string cancelarAsimilable) {
            this.cancelarAsimilable = cancelarAsimilable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelarAsimilableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cancelarAsimilableResult;
        
        public cancelarAsimilableResponse() {
        }
        
        public cancelarAsimilableResponse(string cancelarAsimilableResult) {
            this.cancelarAsimilableResult = cancelarAsimilableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelarPensionadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cancelarPensionado;
        
        public cancelarPensionadoRequest() {
        }
        
        public cancelarPensionadoRequest(string cancelarPensionado) {
            this.cancelarPensionado = cancelarPensionado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelarPensionadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cancelarPensionadoResult;
        
        public cancelarPensionadoResponse() {
        }
        
        public cancelarPensionadoResponse(string cancelarPensionadoResult) {
            this.cancelarPensionadoResult = cancelarPensionadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelarJubiladoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cancelarJubilado;
        
        public cancelarJubiladoRequest() {
        }
        
        public cancelarJubiladoRequest(string cancelarJubilado) {
            this.cancelarJubilado = cancelarJubilado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelarJubiladoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cancelarJubiladoResult;
        
        public cancelarJubiladoResponse() {
        }
        
        public cancelarJubiladoResponse(string cancelarJubiladoResult) {
            this.cancelarJubiladoResult = cancelarJubiladoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerSaldoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string saldoInput;
        
        public obtenerSaldoRequest() {
        }
        
        public obtenerSaldoRequest(string saldoInput) {
            this.saldoInput = saldoInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerSaldoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string saldoResult;
        
        public obtenerSaldoResponse() {
        }
        
        public obtenerSaldoResponse(string saldoResult) {
            this.saldoResult = saldoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarXmlAsalariadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string solicitudFolioAsalariado;
        
        public solicitarXmlAsalariadoRequest() {
        }
        
        public solicitarXmlAsalariadoRequest(string solicitudFolioAsalariado) {
            this.solicitudFolioAsalariado = solicitudFolioAsalariado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarXmlAsalariadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string solicitudResult;
        
        public solicitarXmlAsalariadoResponse() {
        }
        
        public solicitarXmlAsalariadoResponse(string solicitudResult) {
            this.solicitudResult = solicitudResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarXmlAsimilableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string solicitudFolioAsimilable;
        
        public solicitarXmlAsimilableRequest() {
        }
        
        public solicitarXmlAsimilableRequest(string solicitudFolioAsimilable) {
            this.solicitudFolioAsimilable = solicitudFolioAsimilable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarXmlAsimilableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string solicitudResult;
        
        public solicitarXmlAsimilableResponse() {
        }
        
        public solicitarXmlAsimilableResponse(string solicitudResult) {
            this.solicitudResult = solicitudResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarXmlPensionadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string solicitudFolioPensionado;
        
        public solicitarXmlPensionadoRequest() {
        }
        
        public solicitarXmlPensionadoRequest(string solicitudFolioPensionado) {
            this.solicitudFolioPensionado = solicitudFolioPensionado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarXmlPensionadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string solicitudResult;
        
        public solicitarXmlPensionadoResponse() {
        }
        
        public solicitarXmlPensionadoResponse(string solicitudResult) {
            this.solicitudResult = solicitudResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarXmlJubiladoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string solicitudFolioJubilado;
        
        public solicitarXmlJubiladoRequest() {
        }
        
        public solicitarXmlJubiladoRequest(string solicitudFolioJubilado) {
            this.solicitudFolioJubilado = solicitudFolioJubilado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarXmlJubiladoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string solicitudResult;
        
        public solicitarXmlJubiladoResponse() {
        }
        
        public solicitarXmlJubiladoResponse(string solicitudResult) {
            this.solicitudResult = solicitudResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class probarConexionAsimilableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string probarConexionAsimilable;
        
        public probarConexionAsimilableRequest() {
        }
        
        public probarConexionAsimilableRequest(string probarConexionAsimilable) {
            this.probarConexionAsimilable = probarConexionAsimilable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class probarConexionAsimilableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string probarConexionAsimilableResult;
        
        public probarConexionAsimilableResponse() {
        }
        
        public probarConexionAsimilableResponse(string probarConexionAsimilableResult) {
            this.probarConexionAsimilableResult = probarConexionAsimilableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class probarConexionAsalariadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string probarConexionAsalariado;
        
        public probarConexionAsalariadoRequest() {
        }
        
        public probarConexionAsalariadoRequest(string probarConexionAsalariado) {
            this.probarConexionAsalariado = probarConexionAsalariado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class probarConexionAsalariadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string probarConexionAsalariadoResult;
        
        public probarConexionAsalariadoResponse() {
        }
        
        public probarConexionAsalariadoResponse(string probarConexionAsalariadoResult) {
            this.probarConexionAsalariadoResult = probarConexionAsalariadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class probarConexionPensionadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string probarConexionPensionado;
        
        public probarConexionPensionadoRequest() {
        }
        
        public probarConexionPensionadoRequest(string probarConexionPensionado) {
            this.probarConexionPensionado = probarConexionPensionado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class probarConexionPensionadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string probarConexionPensionadoResult;
        
        public probarConexionPensionadoResponse() {
        }
        
        public probarConexionPensionadoResponse(string probarConexionPensionadoResult) {
            this.probarConexionPensionadoResult = probarConexionPensionadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class probarConexionJubiladoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string probarConexionJubilado;
        
        public probarConexionJubiladoRequest() {
        }
        
        public probarConexionJubiladoRequest(string probarConexionJubilado) {
            this.probarConexionJubilado = probarConexionJubilado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class probarConexionJubiladoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string probarConexionJubiladoResult;
        
        public probarConexionJubiladoResponse() {
        }
        
        public probarConexionJubiladoResponse(string probarConexionJubiladoResult) {
            this.probarConexionJubiladoResult = probarConexionJubiladoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarQrAsalariadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string QRsolicitud;
        
        public solicitarQrAsalariadoRequest() {
        }
        
        public solicitarQrAsalariadoRequest(string QRsolicitud) {
            this.QRsolicitud = QRsolicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarQrAsalariadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string QRsolicitudResult;
        
        public solicitarQrAsalariadoResponse() {
        }
        
        public solicitarQrAsalariadoResponse(string QRsolicitudResult) {
            this.QRsolicitudResult = QRsolicitudResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarQrAsimilableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string QRsolicitud;
        
        public solicitarQrAsimilableRequest() {
        }
        
        public solicitarQrAsimilableRequest(string QRsolicitud) {
            this.QRsolicitud = QRsolicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarQrAsimilableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string QRsolicitudResult;
        
        public solicitarQrAsimilableResponse() {
        }
        
        public solicitarQrAsimilableResponse(string QRsolicitudResult) {
            this.QRsolicitudResult = QRsolicitudResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarQrPensionadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string QRsolicitud;
        
        public solicitarQrPensionadoRequest() {
        }
        
        public solicitarQrPensionadoRequest(string QRsolicitud) {
            this.QRsolicitud = QRsolicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarQrPensionadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string QRsolicitudResult;
        
        public solicitarQrPensionadoResponse() {
        }
        
        public solicitarQrPensionadoResponse(string QRsolicitudResult) {
            this.QRsolicitudResult = QRsolicitudResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarQrJubiladoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string QRsolicitud;
        
        public solicitarQrJubiladoRequest() {
        }
        
        public solicitarQrJubiladoRequest(string QRsolicitud) {
            this.QRsolicitud = QRsolicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class solicitarQrJubiladoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string QRsolicitudResult;
        
        public solicitarQrJubiladoResponse() {
        }
        
        public solicitarQrJubiladoResponse(string QRsolicitudResult) {
            this.QRsolicitudResult = QRsolicitudResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarCorreoAsalariadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enviarCorreoAsalariadosolicitud;
        
        public enviarCorreoAsalariadoRequest() {
        }
        
        public enviarCorreoAsalariadoRequest(string enviarCorreoAsalariadosolicitud) {
            this.enviarCorreoAsalariadosolicitud = enviarCorreoAsalariadosolicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarCorreoAsalariadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enviarCorreoAsalariadosolicitudResult;
        
        public enviarCorreoAsalariadoResponse() {
        }
        
        public enviarCorreoAsalariadoResponse(string enviarCorreoAsalariadosolicitudResult) {
            this.enviarCorreoAsalariadosolicitudResult = enviarCorreoAsalariadosolicitudResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarCorreoAsimilableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enviarCorreoAsimilablesolicitud;
        
        public enviarCorreoAsimilableRequest() {
        }
        
        public enviarCorreoAsimilableRequest(string enviarCorreoAsimilablesolicitud) {
            this.enviarCorreoAsimilablesolicitud = enviarCorreoAsimilablesolicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarCorreoAsimilableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enviarCorreoAsimilablesolicitudResult;
        
        public enviarCorreoAsimilableResponse() {
        }
        
        public enviarCorreoAsimilableResponse(string enviarCorreoAsimilablesolicitudResult) {
            this.enviarCorreoAsimilablesolicitudResult = enviarCorreoAsimilablesolicitudResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarCorreoPensionadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enviarCorreoPensionadosolicitud;
        
        public enviarCorreoPensionadoRequest() {
        }
        
        public enviarCorreoPensionadoRequest(string enviarCorreoPensionadosolicitud) {
            this.enviarCorreoPensionadosolicitud = enviarCorreoPensionadosolicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarCorreoPensionadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enviarCorreoPensionadosolicitudResult;
        
        public enviarCorreoPensionadoResponse() {
        }
        
        public enviarCorreoPensionadoResponse(string enviarCorreoPensionadosolicitudResult) {
            this.enviarCorreoPensionadosolicitudResult = enviarCorreoPensionadosolicitudResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarCorreoJubiladoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enviarCorreoJubiladosolicitud;
        
        public enviarCorreoJubiladoRequest() {
        }
        
        public enviarCorreoJubiladoRequest(string enviarCorreoJubiladosolicitud) {
            this.enviarCorreoJubiladosolicitud = enviarCorreoJubiladosolicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enviarCorreoJubiladoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enviarCorreoJubiladosolicitudResult;
        
        public enviarCorreoJubiladoResponse() {
        }
        
        public enviarCorreoJubiladoResponse(string enviarCorreoJubiladosolicitudResult) {
            this.enviarCorreoJubiladosolicitudResult = enviarCorreoJubiladosolicitudResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsAPIxmlSOAPChannel : winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsAPIxmlSOAPClient : System.ServiceModel.ClientBase<winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP>, winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP {
        
        public wsAPIxmlSOAPClient() {
        }
        
        public wsAPIxmlSOAPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsAPIxmlSOAPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAPIxmlSOAPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAPIxmlSOAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.generarAsalariadoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.generarAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.generarAsalariadoRequest request) {
            return base.Channel.generarAsalariado(request);
        }
        
        public string generarAsalariado(string generarAsalariado1) {
            winAppSAIC.srvComEnlaceFiscalAPI.generarAsalariadoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.generarAsalariadoRequest();
            inValue.generarAsalariado = generarAsalariado1;
            winAppSAIC.srvComEnlaceFiscalAPI.generarAsalariadoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).generarAsalariado(inValue);
            return retVal.generarAsalariadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.generarAsimilableResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.generarAsimilable(winAppSAIC.srvComEnlaceFiscalAPI.generarAsimilableRequest request) {
            return base.Channel.generarAsimilable(request);
        }
        
        public string generarAsimilable(string generarAsimilable1) {
            winAppSAIC.srvComEnlaceFiscalAPI.generarAsimilableRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.generarAsimilableRequest();
            inValue.generarAsimilable = generarAsimilable1;
            winAppSAIC.srvComEnlaceFiscalAPI.generarAsimilableResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).generarAsimilable(inValue);
            return retVal.generarAsimilableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.generarPensionadoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.generarPensionado(winAppSAIC.srvComEnlaceFiscalAPI.generarPensionadoRequest request) {
            return base.Channel.generarPensionado(request);
        }
        
        public string generarPensionado(string generarPensionado1) {
            winAppSAIC.srvComEnlaceFiscalAPI.generarPensionadoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.generarPensionadoRequest();
            inValue.generarPensionado = generarPensionado1;
            winAppSAIC.srvComEnlaceFiscalAPI.generarPensionadoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).generarPensionado(inValue);
            return retVal.generarPensionadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.generarJubiladoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.generarJubilado(winAppSAIC.srvComEnlaceFiscalAPI.generarJubiladoRequest request) {
            return base.Channel.generarJubilado(request);
        }
        
        public string generarJubilado(string generarJubilado1) {
            winAppSAIC.srvComEnlaceFiscalAPI.generarJubiladoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.generarJubiladoRequest();
            inValue.generarJubilado = generarJubilado1;
            winAppSAIC.srvComEnlaceFiscalAPI.generarJubiladoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).generarJubilado(inValue);
            return retVal.generarJubiladoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.recuperarAsalariadoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.recuperarAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.recuperarAsalariadoRequest request) {
            return base.Channel.recuperarAsalariado(request);
        }
        
        public string recuperarAsalariado(string recuperarAsalariado1) {
            winAppSAIC.srvComEnlaceFiscalAPI.recuperarAsalariadoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.recuperarAsalariadoRequest();
            inValue.recuperarAsalariado = recuperarAsalariado1;
            winAppSAIC.srvComEnlaceFiscalAPI.recuperarAsalariadoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).recuperarAsalariado(inValue);
            return retVal.recuperarAsalariadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.informacionAsalariadoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.informacionAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.informacionAsalariadoRequest request) {
            return base.Channel.informacionAsalariado(request);
        }
        
        public string informacionAsalariado(string infoFolio) {
            winAppSAIC.srvComEnlaceFiscalAPI.informacionAsalariadoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.informacionAsalariadoRequest();
            inValue.infoFolio = infoFolio;
            winAppSAIC.srvComEnlaceFiscalAPI.informacionAsalariadoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).informacionAsalariado(inValue);
            return retVal.infoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.informacionAsimilableResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.informacionAsimilable(winAppSAIC.srvComEnlaceFiscalAPI.informacionAsimilableRequest request) {
            return base.Channel.informacionAsimilable(request);
        }
        
        public string informacionAsimilable(string infoFolio) {
            winAppSAIC.srvComEnlaceFiscalAPI.informacionAsimilableRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.informacionAsimilableRequest();
            inValue.infoFolio = infoFolio;
            winAppSAIC.srvComEnlaceFiscalAPI.informacionAsimilableResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).informacionAsimilable(inValue);
            return retVal.infoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.informacionPensionadoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.informacionPensionado(winAppSAIC.srvComEnlaceFiscalAPI.informacionPensionadoRequest request) {
            return base.Channel.informacionPensionado(request);
        }
        
        public string informacionPensionado(string infoFolio) {
            winAppSAIC.srvComEnlaceFiscalAPI.informacionPensionadoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.informacionPensionadoRequest();
            inValue.infoFolio = infoFolio;
            winAppSAIC.srvComEnlaceFiscalAPI.informacionPensionadoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).informacionPensionado(inValue);
            return retVal.infoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.informacionJubiladoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.informacionJubilado(winAppSAIC.srvComEnlaceFiscalAPI.informacionJubiladoRequest request) {
            return base.Channel.informacionJubilado(request);
        }
        
        public string informacionJubilado(string infoFolio) {
            winAppSAIC.srvComEnlaceFiscalAPI.informacionJubiladoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.informacionJubiladoRequest();
            inValue.infoFolio = infoFolio;
            winAppSAIC.srvComEnlaceFiscalAPI.informacionJubiladoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).informacionJubilado(inValue);
            return retVal.infoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.cancelarAsalariadoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.cancelarAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.cancelarAsalariadoRequest request) {
            return base.Channel.cancelarAsalariado(request);
        }
        
        public string cancelarAsalariado(string cancelarAsalariado1) {
            winAppSAIC.srvComEnlaceFiscalAPI.cancelarAsalariadoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.cancelarAsalariadoRequest();
            inValue.cancelarAsalariado = cancelarAsalariado1;
            winAppSAIC.srvComEnlaceFiscalAPI.cancelarAsalariadoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).cancelarAsalariado(inValue);
            return retVal.cancelarAsalariadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.cancelarAsimilableResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.cancelarAsimilable(winAppSAIC.srvComEnlaceFiscalAPI.cancelarAsimilableRequest request) {
            return base.Channel.cancelarAsimilable(request);
        }
        
        public string cancelarAsimilable(string cancelarAsimilable1) {
            winAppSAIC.srvComEnlaceFiscalAPI.cancelarAsimilableRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.cancelarAsimilableRequest();
            inValue.cancelarAsimilable = cancelarAsimilable1;
            winAppSAIC.srvComEnlaceFiscalAPI.cancelarAsimilableResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).cancelarAsimilable(inValue);
            return retVal.cancelarAsimilableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.cancelarPensionadoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.cancelarPensionado(winAppSAIC.srvComEnlaceFiscalAPI.cancelarPensionadoRequest request) {
            return base.Channel.cancelarPensionado(request);
        }
        
        public string cancelarPensionado(string cancelarPensionado1) {
            winAppSAIC.srvComEnlaceFiscalAPI.cancelarPensionadoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.cancelarPensionadoRequest();
            inValue.cancelarPensionado = cancelarPensionado1;
            winAppSAIC.srvComEnlaceFiscalAPI.cancelarPensionadoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).cancelarPensionado(inValue);
            return retVal.cancelarPensionadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.cancelarJubiladoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.cancelarJubilado(winAppSAIC.srvComEnlaceFiscalAPI.cancelarJubiladoRequest request) {
            return base.Channel.cancelarJubilado(request);
        }
        
        public string cancelarJubilado(string cancelarJubilado1) {
            winAppSAIC.srvComEnlaceFiscalAPI.cancelarJubiladoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.cancelarJubiladoRequest();
            inValue.cancelarJubilado = cancelarJubilado1;
            winAppSAIC.srvComEnlaceFiscalAPI.cancelarJubiladoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).cancelarJubilado(inValue);
            return retVal.cancelarJubiladoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.obtenerSaldoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.obtenerSaldo(winAppSAIC.srvComEnlaceFiscalAPI.obtenerSaldoRequest request) {
            return base.Channel.obtenerSaldo(request);
        }
        
        public string obtenerSaldo(string saldoInput) {
            winAppSAIC.srvComEnlaceFiscalAPI.obtenerSaldoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.obtenerSaldoRequest();
            inValue.saldoInput = saldoInput;
            winAppSAIC.srvComEnlaceFiscalAPI.obtenerSaldoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).obtenerSaldo(inValue);
            return retVal.saldoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlAsalariadoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.solicitarXmlAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlAsalariadoRequest request) {
            return base.Channel.solicitarXmlAsalariado(request);
        }
        
        public string solicitarXmlAsalariado(string solicitudFolioAsalariado) {
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlAsalariadoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlAsalariadoRequest();
            inValue.solicitudFolioAsalariado = solicitudFolioAsalariado;
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlAsalariadoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).solicitarXmlAsalariado(inValue);
            return retVal.solicitudResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlAsimilableResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.solicitarXmlAsimilable(winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlAsimilableRequest request) {
            return base.Channel.solicitarXmlAsimilable(request);
        }
        
        public string solicitarXmlAsimilable(string solicitudFolioAsimilable) {
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlAsimilableRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlAsimilableRequest();
            inValue.solicitudFolioAsimilable = solicitudFolioAsimilable;
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlAsimilableResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).solicitarXmlAsimilable(inValue);
            return retVal.solicitudResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlPensionadoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.solicitarXmlPensionado(winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlPensionadoRequest request) {
            return base.Channel.solicitarXmlPensionado(request);
        }
        
        public string solicitarXmlPensionado(string solicitudFolioPensionado) {
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlPensionadoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlPensionadoRequest();
            inValue.solicitudFolioPensionado = solicitudFolioPensionado;
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlPensionadoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).solicitarXmlPensionado(inValue);
            return retVal.solicitudResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlJubiladoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.solicitarXmlJubilado(winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlJubiladoRequest request) {
            return base.Channel.solicitarXmlJubilado(request);
        }
        
        public string solicitarXmlJubilado(string solicitudFolioJubilado) {
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlJubiladoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlJubiladoRequest();
            inValue.solicitudFolioJubilado = solicitudFolioJubilado;
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarXmlJubiladoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).solicitarXmlJubilado(inValue);
            return retVal.solicitudResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.probarConexionAsimilableResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.probarConexionAsimilable(winAppSAIC.srvComEnlaceFiscalAPI.probarConexionAsimilableRequest request) {
            return base.Channel.probarConexionAsimilable(request);
        }
        
        public string probarConexionAsimilable(string probarConexionAsimilable1) {
            winAppSAIC.srvComEnlaceFiscalAPI.probarConexionAsimilableRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.probarConexionAsimilableRequest();
            inValue.probarConexionAsimilable = probarConexionAsimilable1;
            winAppSAIC.srvComEnlaceFiscalAPI.probarConexionAsimilableResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).probarConexionAsimilable(inValue);
            return retVal.probarConexionAsimilableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.probarConexionAsalariadoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.probarConexionAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.probarConexionAsalariadoRequest request) {
            return base.Channel.probarConexionAsalariado(request);
        }
        
        public string probarConexionAsalariado(string probarConexionAsalariado1) {
            winAppSAIC.srvComEnlaceFiscalAPI.probarConexionAsalariadoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.probarConexionAsalariadoRequest();
            inValue.probarConexionAsalariado = probarConexionAsalariado1;
            winAppSAIC.srvComEnlaceFiscalAPI.probarConexionAsalariadoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).probarConexionAsalariado(inValue);
            return retVal.probarConexionAsalariadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.probarConexionPensionadoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.probarConexionPensionado(winAppSAIC.srvComEnlaceFiscalAPI.probarConexionPensionadoRequest request) {
            return base.Channel.probarConexionPensionado(request);
        }
        
        public string probarConexionPensionado(string probarConexionPensionado1) {
            winAppSAIC.srvComEnlaceFiscalAPI.probarConexionPensionadoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.probarConexionPensionadoRequest();
            inValue.probarConexionPensionado = probarConexionPensionado1;
            winAppSAIC.srvComEnlaceFiscalAPI.probarConexionPensionadoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).probarConexionPensionado(inValue);
            return retVal.probarConexionPensionadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.probarConexionJubiladoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.probarConexionJubilado(winAppSAIC.srvComEnlaceFiscalAPI.probarConexionJubiladoRequest request) {
            return base.Channel.probarConexionJubilado(request);
        }
        
        public string probarConexionJubilado(string probarConexionJubilado1) {
            winAppSAIC.srvComEnlaceFiscalAPI.probarConexionJubiladoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.probarConexionJubiladoRequest();
            inValue.probarConexionJubilado = probarConexionJubilado1;
            winAppSAIC.srvComEnlaceFiscalAPI.probarConexionJubiladoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).probarConexionJubilado(inValue);
            return retVal.probarConexionJubiladoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrAsalariadoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.solicitarQrAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrAsalariadoRequest request) {
            return base.Channel.solicitarQrAsalariado(request);
        }
        
        public string solicitarQrAsalariado(string QRsolicitud) {
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrAsalariadoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrAsalariadoRequest();
            inValue.QRsolicitud = QRsolicitud;
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrAsalariadoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).solicitarQrAsalariado(inValue);
            return retVal.QRsolicitudResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrAsimilableResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.solicitarQrAsimilable(winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrAsimilableRequest request) {
            return base.Channel.solicitarQrAsimilable(request);
        }
        
        public string solicitarQrAsimilable(string QRsolicitud) {
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrAsimilableRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrAsimilableRequest();
            inValue.QRsolicitud = QRsolicitud;
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrAsimilableResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).solicitarQrAsimilable(inValue);
            return retVal.QRsolicitudResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrPensionadoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.solicitarQrPensionado(winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrPensionadoRequest request) {
            return base.Channel.solicitarQrPensionado(request);
        }
        
        public string solicitarQrPensionado(string QRsolicitud) {
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrPensionadoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrPensionadoRequest();
            inValue.QRsolicitud = QRsolicitud;
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrPensionadoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).solicitarQrPensionado(inValue);
            return retVal.QRsolicitudResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrJubiladoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.solicitarQrJubilado(winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrJubiladoRequest request) {
            return base.Channel.solicitarQrJubilado(request);
        }
        
        public string solicitarQrJubilado(string QRsolicitud) {
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrJubiladoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrJubiladoRequest();
            inValue.QRsolicitud = QRsolicitud;
            winAppSAIC.srvComEnlaceFiscalAPI.solicitarQrJubiladoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).solicitarQrJubilado(inValue);
            return retVal.QRsolicitudResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoAsalariadoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.enviarCorreoAsalariado(winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoAsalariadoRequest request) {
            return base.Channel.enviarCorreoAsalariado(request);
        }
        
        public string enviarCorreoAsalariado(string enviarCorreoAsalariadosolicitud) {
            winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoAsalariadoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoAsalariadoRequest();
            inValue.enviarCorreoAsalariadosolicitud = enviarCorreoAsalariadosolicitud;
            winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoAsalariadoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).enviarCorreoAsalariado(inValue);
            return retVal.enviarCorreoAsalariadosolicitudResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoAsimilableResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.enviarCorreoAsimilable(winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoAsimilableRequest request) {
            return base.Channel.enviarCorreoAsimilable(request);
        }
        
        public string enviarCorreoAsimilable(string enviarCorreoAsimilablesolicitud) {
            winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoAsimilableRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoAsimilableRequest();
            inValue.enviarCorreoAsimilablesolicitud = enviarCorreoAsimilablesolicitud;
            winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoAsimilableResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).enviarCorreoAsimilable(inValue);
            return retVal.enviarCorreoAsimilablesolicitudResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoPensionadoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.enviarCorreoPensionado(winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoPensionadoRequest request) {
            return base.Channel.enviarCorreoPensionado(request);
        }
        
        public string enviarCorreoPensionado(string enviarCorreoPensionadosolicitud) {
            winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoPensionadoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoPensionadoRequest();
            inValue.enviarCorreoPensionadosolicitud = enviarCorreoPensionadosolicitud;
            winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoPensionadoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).enviarCorreoPensionado(inValue);
            return retVal.enviarCorreoPensionadosolicitudResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoJubiladoResponse winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP.enviarCorreoJubilado(winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoJubiladoRequest request) {
            return base.Channel.enviarCorreoJubilado(request);
        }
        
        public string enviarCorreoJubilado(string enviarCorreoJubiladosolicitud) {
            winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoJubiladoRequest inValue = new winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoJubiladoRequest();
            inValue.enviarCorreoJubiladosolicitud = enviarCorreoJubiladosolicitud;
            winAppSAIC.srvComEnlaceFiscalAPI.enviarCorreoJubiladoResponse retVal = ((winAppSAIC.srvComEnlaceFiscalAPI.wsAPIxmlSOAP)(this)).enviarCorreoJubilado(inValue);
            return retVal.enviarCorreoJubiladosolicitudResult;
        }
    }
}
