#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winAppSAIC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbSAICBPO_MX")]
	public partial class dbSAICBPOCatalogosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dbSAICBPOCatalogosDataContext() : 
				base(global::winAppSAIC.Properties.Settings.Default.dbSAICBPOConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbSAICBPOCatalogosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbSAICBPOCatalogosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbSAICBPOCatalogosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbSAICBPOCatalogosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stpSelInfoConfiguracionNotificaciones")]
		public ISingleResult<stpSelInfoConfiguracionNotificacionesResult> stpSelInfoConfiguracionNotificaciones([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pDescFuncionalidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pDescFuncionalidad);
			return ((ISingleResult<stpSelInfoConfiguracionNotificacionesResult>)(result.ReturnValue));
		}
	}
	
	public partial class stpSelInfoConfiguracionNotificacionesResult
	{
		
		private short _IdConfiguracionNotificaciones;
		
		private string _DescFuncionalidad;
		
		private string _SMTPServer;
		
		private string _EmailUser;
		
		private string _EmailPassword;
		
		private string _Puerto;
		
		private bool _FormatoHTML;
		
		private bool _SSL;
		
		public stpSelInfoConfiguracionNotificacionesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdConfiguracionNotificaciones", DbType="SmallInt NOT NULL")]
		public short IdConfiguracionNotificaciones
		{
			get
			{
				return this._IdConfiguracionNotificaciones;
			}
			set
			{
				if ((this._IdConfiguracionNotificaciones != value))
				{
					this._IdConfiguracionNotificaciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescFuncionalidad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DescFuncionalidad
		{
			get
			{
				return this._DescFuncionalidad;
			}
			set
			{
				if ((this._DescFuncionalidad != value))
				{
					this._DescFuncionalidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMTPServer", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SMTPServer
		{
			get
			{
				return this._SMTPServer;
			}
			set
			{
				if ((this._SMTPServer != value))
				{
					this._SMTPServer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailUser", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailUser
		{
			get
			{
				return this._EmailUser;
			}
			set
			{
				if ((this._EmailUser != value))
				{
					this._EmailUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailPassword", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailPassword
		{
			get
			{
				return this._EmailPassword;
			}
			set
			{
				if ((this._EmailPassword != value))
				{
					this._EmailPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puerto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Puerto
		{
			get
			{
				return this._Puerto;
			}
			set
			{
				if ((this._Puerto != value))
				{
					this._Puerto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormatoHTML", DbType="Bit NOT NULL")]
		public bool FormatoHTML
		{
			get
			{
				return this._FormatoHTML;
			}
			set
			{
				if ((this._FormatoHTML != value))
				{
					this._FormatoHTML = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSL", DbType="Bit NOT NULL")]
		public bool SSL
		{
			get
			{
				return this._SSL;
			}
			set
			{
				if ((this._SSL != value))
				{
					this._SSL = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
