//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winAppSAIC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://facturacion.finkok.com/servicios/soap/stamp")]
        public string winAppSAIC_Timbrefinkok_StampSOAP {
            get {
                return ((string)(this["winAppSAIC_Timbrefinkok_StampSOAP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://facturacion.finkok.com/servicios/soap/cancel")]
        public string winAppSAIC_finkokdemoCancelar_CancelSOAP {
            get {
                return ((string)(this["winAppSAIC_finkokdemoCancelar_CancelSOAP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.facturacionmexico.com.mx/pac/index.php")]
        public string winAppSAIC_ThreeBits_wservice {
            get {
                return ((string)(this["winAppSAIC_ThreeBits_wservice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pac1.facturacionmexico.com.mx/cancelacion2022/index.php")]
        public string winAppSAIC_ThreeBitsCancelar_Cancelar_cfdi_3_3_SAT {
            get {
                return ((string)(this["winAppSAIC_ThreeBitsCancelar_Cancelar_cfdi_3_3_SAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=saicadna.ddns.net,1433;Initial Catalog=msdb;Persist Security Info=Tru" +
            "e;User ID=dbUserJOBs;Password=+ON>E7n9Je(E5&21")]
        public string dbSAICBPOConnectionStringJOB {
            get {
                return ((string)(this["dbSAICBPOConnectionStringJOB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=saicadna.ddns.net,1433;Initial Catalog=dbADNA_ASIM_MX_20240229;User I" +
            "D=dbUserAsimiladosMX;Password=e@}s[BB$q#?G6QTz")]
        public string dbSAICBPOConnectionStringAsimilados {
            get {
                return ((string)(this["dbSAICBPOConnectionStringAsimilados"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=saicadna.ddns.net,1433;Initial Catalog=dbADNA_PENSION_MX_20240229;Per" +
            "sist Security Info=True;User ID=mario.flores;Password=m@lbErt2202Flo&3z;Connect " +
            "Timeout=15;Application Name=\"SAIC Pensiones 2017\"")]
        public string dbSAICBPOConnectionString {
            get {
                return ((string)(this["dbSAICBPOConnectionString"]));
            }
        }
    }
}
