//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winAppSAIC.LucasServ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="objComprobante33", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class objComprobante33 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtraInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeIncidenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bGeneradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strComprobanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoErrorField, value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraInfo {
            get {
                return this.ExtraInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraInfoField, value) != true)) {
                    this.ExtraInfoField = value;
                    this.RaisePropertyChanged("ExtraInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeIncidencia {
            get {
                return this.MensajeIncidenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeIncidenciaField, value) != true)) {
                    this.MensajeIncidenciaField = value;
                    this.RaisePropertyChanged("MensajeIncidencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bGenerado {
            get {
                return this.bGeneradoField;
            }
            set {
                if ((this.bGeneradoField.Equals(value) != true)) {
                    this.bGeneradoField = value;
                    this.RaisePropertyChanged("bGenerado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strComprobante {
            get {
                return this.strComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.strComprobanteField, value) != true)) {
                    this.strComprobanteField = value;
                    this.RaisePropertyChanged("strComprobante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LucasServ.IFacturacion33Service")]
    public interface IFacturacion33Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturacion33Service/GenerarComprobante", ReplyAction="http://tempuri.org/IFacturacion33Service/GenerarComprobanteResponse")]
        winAppSAIC.LucasServ.objComprobante33 GenerarComprobante(string cGuid, string strComprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacturacion33Service/GenerarComprobanteSellado", ReplyAction="http://tempuri.org/IFacturacion33Service/GenerarComprobanteSelladoResponse")]
        winAppSAIC.LucasServ.objComprobante33 GenerarComprobanteSellado(string cGuid, string strComprobante);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFacturacion33ServiceChannel : winAppSAIC.LucasServ.IFacturacion33Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Facturacion33ServiceClient : System.ServiceModel.ClientBase<winAppSAIC.LucasServ.IFacturacion33Service>, winAppSAIC.LucasServ.IFacturacion33Service {
        
        public Facturacion33ServiceClient() {
        }
        
        public Facturacion33ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Facturacion33ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Facturacion33ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Facturacion33ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public winAppSAIC.LucasServ.objComprobante33 GenerarComprobante(string cGuid, string strComprobante) {
            return base.Channel.GenerarComprobante(cGuid, strComprobante);
        }
        
        public winAppSAIC.LucasServ.objComprobante33 GenerarComprobanteSellado(string cGuid, string strComprobante) {
            return base.Channel.GenerarComprobanteSellado(cGuid, strComprobante);
        }
    }
}
