//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winAppSAIC.NominaCFDITimbreFacil
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class dbSAICBPO_PENSION_MX2017Entities : DbContext
    {
        public dbSAICBPO_PENSION_MX2017Entities()
            : base("name=dbSAICBPO_PENSION_MX2017Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<stpSelDetalleNominaTimbreFacilCFDI_Result> stpSelDetalleNominaTimbreFacilCFDI(Nullable<long> pIdLoteCargaNomina, Nullable<long> pIdPDOHeader, string pIdTipoMovimiento)
        {
            var pIdLoteCargaNominaParameter = pIdLoteCargaNomina.HasValue ?
                new ObjectParameter("pIdLoteCargaNomina", pIdLoteCargaNomina) :
                new ObjectParameter("pIdLoteCargaNomina", typeof(long));
    
            var pIdPDOHeaderParameter = pIdPDOHeader.HasValue ?
                new ObjectParameter("pIdPDOHeader", pIdPDOHeader) :
                new ObjectParameter("pIdPDOHeader", typeof(long));
    
            var pIdTipoMovimientoParameter = pIdTipoMovimiento != null ?
                new ObjectParameter("pIdTipoMovimiento", pIdTipoMovimiento) :
                new ObjectParameter("pIdTipoMovimiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stpSelDetalleNominaTimbreFacilCFDI_Result>("stpSelDetalleNominaTimbreFacilCFDI", pIdLoteCargaNominaParameter, pIdPDOHeaderParameter, pIdTipoMovimientoParameter);
        }
    
        public virtual ObjectResult<stpSelPercepcionesDeduccionesGravadoExentoTimbreFacil_Result> stpSelPercepcionesDeduccionesGravadoExentoTimbreFacil(Nullable<long> pIdLoteCargaNomina, string pTipoMovimiento)
        {
            var pIdLoteCargaNominaParameter = pIdLoteCargaNomina.HasValue ?
                new ObjectParameter("pIdLoteCargaNomina", pIdLoteCargaNomina) :
                new ObjectParameter("pIdLoteCargaNomina", typeof(long));
    
            var pTipoMovimientoParameter = pTipoMovimiento != null ?
                new ObjectParameter("pTipoMovimiento", pTipoMovimiento) :
                new ObjectParameter("pTipoMovimiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stpSelPercepcionesDeduccionesGravadoExentoTimbreFacil_Result>("stpSelPercepcionesDeduccionesGravadoExentoTimbreFacil", pIdLoteCargaNominaParameter, pTipoMovimientoParameter);
        }
    
        public virtual ObjectResult<stpSelPercepcionesDeduccionesGravadoExentoTimbreFacilv12_Result> stpSelPercepcionesDeduccionesGravadoExentoTimbreFacilv12(Nullable<long> pIdLoteCargaNomina, string pTipoMovimiento)
        {
            var pIdLoteCargaNominaParameter = pIdLoteCargaNomina.HasValue ?
                new ObjectParameter("pIdLoteCargaNomina", pIdLoteCargaNomina) :
                new ObjectParameter("pIdLoteCargaNomina", typeof(long));
    
            var pTipoMovimientoParameter = pTipoMovimiento != null ?
                new ObjectParameter("pTipoMovimiento", pTipoMovimiento) :
                new ObjectParameter("pTipoMovimiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stpSelPercepcionesDeduccionesGravadoExentoTimbreFacilv12_Result>("stpSelPercepcionesDeduccionesGravadoExentoTimbreFacilv12", pIdLoteCargaNominaParameter, pTipoMovimientoParameter);
        }
    
        public virtual ObjectResult<stpSelDetalleNominaTimbreFacilCFDIv12_Result> stpSelDetalleNominaTimbreFacilCFDIv12(Nullable<long> pIdLoteCargaNomina, Nullable<long> pIdPDOHeader, string pIdTipoMovimiento)
        {
            var pIdLoteCargaNominaParameter = pIdLoteCargaNomina.HasValue ?
                new ObjectParameter("pIdLoteCargaNomina", pIdLoteCargaNomina) :
                new ObjectParameter("pIdLoteCargaNomina", typeof(long));
    
            var pIdPDOHeaderParameter = pIdPDOHeader.HasValue ?
                new ObjectParameter("pIdPDOHeader", pIdPDOHeader) :
                new ObjectParameter("pIdPDOHeader", typeof(long));
    
            var pIdTipoMovimientoParameter = pIdTipoMovimiento != null ?
                new ObjectParameter("pIdTipoMovimiento", pIdTipoMovimiento) :
                new ObjectParameter("pIdTipoMovimiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stpSelDetalleNominaTimbreFacilCFDIv12_Result>("stpSelDetalleNominaTimbreFacilCFDIv12", pIdLoteCargaNominaParameter, pIdPDOHeaderParameter, pIdTipoMovimientoParameter);
        }
    }
}
